version: "3.8"

services:
  web:
    container_name: web
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./backend/

    env_file:
      - "./.env"

    environment:
      - WATCHFILES_FORCE_POLLING=true

    volumes:
      - ./backend/src/:/usr/backend/src/
      - ./backend/tests/:/usr/backend/tests/
    ports:
      - 8001:8000

    depends_on:
      - jfat_dev_db_host
      - jfat_test_db_host

  jfat_dev_db_host:
    container_name: jfat_dev_db_host
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - "./.env"

    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DEV_DB}
      - PGDATA=/var/lib/postgresql/data/

    expose:
      - 5432
    ports:
      - 5431:5432

  jfat_test_db_host:
    container_name: jfat_test_db_host
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - "./.env"

    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
      - PGDATA=/var/lib/postgresql/data/

    expose:
      - 5432
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    env_file:
      - "./.env"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_DEV_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    expose:
      - 8080
    ports:
      - 8081:8080
    depends_on:
      - jfat_dev_db_host

  test_adminer:
    image: adminer
    container_name: test_db_adminer
    restart: always
    env_file:
      - "./.env"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_TEST_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    expose:
      - 8080
    ports:
      - 8082:8080
    depends_on:
      - jfat_test_db_host

volumes:
  postgres_data:
  postgres_test_data:
